// TODO: Move most of this file entirely to the prisma database
// TODO: Setup a seed variable JSON file that contains this data instead.

import { type Sort } from './request-helper'

export const METABASE_BOT_ID = 'metabase_bot_cjkhd7gxs0000rtxs3x2r0k7l'

export const MOCK_CODE_GITHUB = 'MOCK_CODE_GITHUB_KODY'
export const MOCK_CODE_GITHUB_HEADER = 'x-mock-code-github'

export const COUNTRIES = [
	{
		iso_3166_1: 'AD',
		name: 'Andorra',
		nativeName: 'Andorra',
		flag: '🇦🇩',
	},
	{
		iso_3166_1: 'AE',
		name: 'United Arab Emirates',
		nativeName: 'United Arab Emirates',
		flag: '🇦🇪',
	},
	{
		iso_3166_1: 'AF',
		name: 'Afghanistan',
		nativeName: 'Afghanistan',
		flag: '🇦🇫',
	},
	{
		iso_3166_1: 'AG',
		name: 'Antigua and Barbuda',
		nativeName: 'Antigua & Barbuda',
		flag: '🇦🇬',
	},
	{
		iso_3166_1: 'AI',
		name: 'Anguilla',
		nativeName: 'Anguilla',
		flag: '🇦🇮',
	},
	{
		iso_3166_1: 'AL',
		name: 'Albania',
		nativeName: 'Albania',
		flag: '🇦🇱',
	},
	{
		iso_3166_1: 'AM',
		name: 'Armenia',
		nativeName: 'Armenia',
		flag: '🇦🇲',
	},
	{
		iso_3166_1: 'AN',
		name: 'Netherlands Antilles',
		nativeName: 'Netherlands Antilles',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'AO',
		name: 'Angola',
		nativeName: 'Angola',
		flag: '🇦🇴',
	},
	{
		iso_3166_1: 'AQ',
		name: 'Antarctica',
		nativeName: 'Antarctica',
		flag: '🇦🇶',
	},
	{
		iso_3166_1: 'AR',
		name: 'Argentina',
		nativeName: 'Argentina',
		flag: '🇦🇷',
	},
	{
		iso_3166_1: 'AS',
		name: 'American Samoa',
		nativeName: 'American Samoa',
		flag: '🇦🇸',
	},
	{
		iso_3166_1: 'AT',
		name: 'Austria',
		nativeName: 'Austria',
		flag: '🇦🇹',
	},
	{
		iso_3166_1: 'AU',
		name: 'Australia',
		nativeName: 'Australia',
		flag: '🇦🇺',
	},
	{
		iso_3166_1: 'AW',
		name: 'Aruba',
		nativeName: 'Aruba',
		flag: '🇦🇼',
	},
	{
		iso_3166_1: 'AZ',
		name: 'Azerbaijan',
		nativeName: 'Azerbaijan',
		flag: '🇦🇿',
	},
	{
		iso_3166_1: 'BA',
		name: 'Bosnia and Herzegovina',
		nativeName: 'Bosnia & Herzegovina',
		flag: '🇧🇦',
	},
	{
		iso_3166_1: 'BB',
		name: 'Barbados',
		nativeName: 'Barbados',
		flag: '🇧🇧',
	},
	{
		iso_3166_1: 'BD',
		name: 'Bangladesh',
		nativeName: 'Bangladesh',
		flag: '🇧🇩',
	},
	{
		iso_3166_1: 'BE',
		name: 'Belgium',
		nativeName: 'Belgium',
		flag: '🇧🇪',
	},
	{
		iso_3166_1: 'BF',
		name: 'Burkina Faso',
		nativeName: 'Burkina Faso',
		flag: '🇧🇫',
	},
	{
		iso_3166_1: 'BG',
		name: 'Bulgaria',
		nativeName: 'Bulgaria',
		flag: '🇧🇬',
	},
	{
		iso_3166_1: 'BH',
		name: 'Bahrain',
		nativeName: 'Bahrain',
		flag: '🇧🇭',
	},
	{
		iso_3166_1: 'BI',
		name: 'Burundi',
		nativeName: 'Burundi',
		flag: '🇧🇮',
	},
	{
		iso_3166_1: 'BJ',
		name: 'Benin',
		nativeName: 'Benin',
		flag: '🇧🇯',
	},
	{
		iso_3166_1: 'BM',
		name: 'Bermuda',
		nativeName: 'Bermuda',
		flag: '🇧🇲',
	},
	{
		iso_3166_1: 'BN',
		name: 'Brunei Darussalam',
		nativeName: 'Brunei',
		flag: '🇧🇳',
	},
	{
		iso_3166_1: 'BO',
		name: 'Bolivia',
		nativeName: 'Bolivia',
		flag: '🇧🇴',
	},
	{
		iso_3166_1: 'BR',
		name: 'Brazil',
		nativeName: 'Brazil',
		flag: '🇧🇷',
	},
	{
		iso_3166_1: 'BS',
		name: 'Bahamas',
		nativeName: 'Bahamas',
		flag: '🇧🇸',
	},
	{
		iso_3166_1: 'BT',
		name: 'Bhutan',
		nativeName: 'Bhutan',
		flag: '🇧🇹',
	},
	{
		iso_3166_1: 'BU',
		name: 'Burma',
		nativeName: 'Burma',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'BV',
		name: 'Bouvet Island',
		nativeName: 'Bouvet Island',
		flag: '🇧🇻',
	},
	{
		iso_3166_1: 'BW',
		name: 'Botswana',
		nativeName: 'Botswana',
		flag: '🇧🇼',
	},
	{
		iso_3166_1: 'BY',
		name: 'Belarus',
		nativeName: 'Belarus',
		flag: '🇧🇾',
	},
	{
		iso_3166_1: 'BZ',
		name: 'Belize',
		nativeName: 'Belize',
		flag: '🇧🇿',
	},
	{
		iso_3166_1: 'CA',
		name: 'Canada',
		nativeName: 'Canada',
		flag: '🇨🇦',
	},
	{
		iso_3166_1: 'CC',
		name: 'Cocos  Islands',
		nativeName: 'Cocos (Keeling) Islands',
		flag: '🇨🇨',
	},
	{
		iso_3166_1: 'CD',
		name: 'Congo',
		nativeName: 'Democratic Republic of the Congo (Kinshasa)',
		flag: '🇨🇩',
	},
	{
		iso_3166_1: 'CF',
		name: 'Central African Republic',
		nativeName: 'Central African Republic',
		flag: '🇨🇫',
	},
	{
		iso_3166_1: 'CG',
		name: 'Congo',
		nativeName: 'Republic of the Congo (Brazzaville)',
		flag: '🇨🇬',
	},
	{
		iso_3166_1: 'CH',
		name: 'Switzerland',
		nativeName: 'Switzerland',
		flag: '🇨🇭',
	},
	{
		iso_3166_1: 'CI',
		name: "Cote D'Ivoire",
		nativeName: 'Côte d’Ivoire',
		flag: '🇨🇮',
	},
	{
		iso_3166_1: 'CK',
		name: 'Cook Islands',
		nativeName: 'Cook Islands',
		flag: '🇨🇰',
	},
	{
		iso_3166_1: 'CL',
		name: 'Chile',
		nativeName: 'Chile',
		flag: '🇨🇱',
	},
	{
		iso_3166_1: 'CM',
		name: 'Cameroon',
		nativeName: 'Cameroon',
		flag: '🇨🇲',
	},
	{
		iso_3166_1: 'CN',
		name: 'China',
		nativeName: 'China',
		flag: '🇨🇳',
	},
	{
		iso_3166_1: 'CO',
		name: 'Colombia',
		nativeName: 'Colombia',
		flag: '🇨🇴',
	},
	{
		iso_3166_1: 'CR',
		name: 'Costa Rica',
		nativeName: 'Costa Rica',
		flag: '🇨🇷',
	},
	{
		iso_3166_1: 'CS',
		name: 'Serbia and Montenegro',
		nativeName: 'Serbia and Montenegro',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'CU',
		name: 'Cuba',
		nativeName: 'Cuba',
		flag: '🇨🇺',
	},
	{
		iso_3166_1: 'CV',
		name: 'Cape Verde',
		nativeName: 'Cape Verde',
		flag: '🇨🇻',
	},
	{
		iso_3166_1: 'CX',
		name: 'Christmas Island',
		nativeName: 'Christmas Island',
		flag: '🇨🇽',
	},
	{
		iso_3166_1: 'CY',
		name: 'Cyprus',
		nativeName: 'Cyprus',
		flag: '🇨🇾',
	},
	{
		iso_3166_1: 'CZ',
		name: 'Czech Republic',
		nativeName: 'Czech Republic',
		flag: '🇨🇿',
	},
	{
		iso_3166_1: 'DE',
		name: 'Germany',
		nativeName: 'Germany',
		flag: '🇩🇪',
	},
	{
		iso_3166_1: 'DJ',
		name: 'Djibouti',
		nativeName: 'Djibouti',
		flag: '🇩🇯',
	},
	{
		iso_3166_1: 'DK',
		name: 'Denmark',
		nativeName: 'Denmark',
		flag: '🇩🇰',
	},
	{
		iso_3166_1: 'DM',
		name: 'Dominica',
		nativeName: 'Dominica',
		flag: '🇩🇲',
	},
	{
		iso_3166_1: 'DO',
		name: 'Dominican Republic',
		nativeName: 'Dominican Republic',
		flag: '🇩🇴',
	},
	{
		iso_3166_1: 'DZ',
		name: 'Algeria',
		nativeName: 'Algeria',
		flag: '🇩🇿',
	},
	{
		iso_3166_1: 'EC',
		name: 'Ecuador',
		nativeName: 'Ecuador',
		flag: '🇪🇨',
	},
	{
		iso_3166_1: 'EE',
		name: 'Estonia',
		nativeName: 'Estonia',
		flag: '🇪🇪',
	},
	{
		iso_3166_1: 'EG',
		name: 'Egypt',
		nativeName: 'Egypt',
		flag: '🇪🇬',
	},
	{
		iso_3166_1: 'EH',
		name: 'Western Sahara',
		nativeName: 'Western Sahara',
		flag: '🇪🇭',
	},
	{
		iso_3166_1: 'ER',
		name: 'Eritrea',
		nativeName: 'Eritrea',
		flag: '🇪🇷',
	},
	{
		iso_3166_1: 'ES',
		name: 'Spain',
		nativeName: 'Spain',
		flag: '🇪🇸',
	},
	{
		iso_3166_1: 'ET',
		name: 'Ethiopia',
		nativeName: 'Ethiopia',
		flag: '🇪🇹',
	},
	{
		iso_3166_1: 'FI',
		name: 'Finland',
		nativeName: 'Finland',
		flag: '🇫🇮',
	},
	{
		iso_3166_1: 'FJ',
		name: 'Fiji',
		nativeName: 'Fiji',
		flag: '🇫🇯',
	},
	{
		iso_3166_1: 'FK',
		name: 'Falkland Islands',
		nativeName: 'Falkland Islands',
		flag: '🇫🇰',
	},
	{
		iso_3166_1: 'FM',
		name: 'Micronesia',
		nativeName: 'Micronesia',
		flag: '🇫🇲',
	},
	{
		iso_3166_1: 'FO',
		name: 'Faeroe Islands',
		nativeName: 'Faroe Islands',
		flag: '🇫🇴',
	},
	{
		iso_3166_1: 'FR',
		name: 'France',
		nativeName: 'France',
		flag: '🇫🇷',
	},
	{
		iso_3166_1: 'GA',
		name: 'Gabon',
		nativeName: 'Gabon',
		flag: '🇬🇦',
	},
	{
		iso_3166_1: 'GB',
		name: 'United Kingdom',
		nativeName: 'United Kingdom',
		flag: '🇬🇧',
	},
	{
		iso_3166_1: 'GD',
		name: 'Grenada',
		nativeName: 'Grenada',
		flag: '🇬🇩',
	},
	{
		iso_3166_1: 'GE',
		name: 'Georgia',
		nativeName: 'Georgia',
		flag: '🇬🇪',
	},
	{
		iso_3166_1: 'GF',
		name: 'French Guiana',
		nativeName: 'French Guiana',
		flag: '🇬🇫',
	},
	{
		iso_3166_1: 'GH',
		name: 'Ghana',
		nativeName: 'Ghana',
		flag: '🇬🇭',
	},
	{
		iso_3166_1: 'GI',
		name: 'Gibraltar',
		nativeName: 'Gibraltar',
		flag: '🇬🇮',
	},
	{
		iso_3166_1: 'GL',
		name: 'Greenland',
		nativeName: 'Greenland',
		flag: '🇬🇱',
	},
	{
		iso_3166_1: 'GM',
		name: 'Gambia',
		nativeName: 'Gambia',
		flag: '🇬🇲',
	},
	{
		iso_3166_1: 'GN',
		name: 'Guinea',
		nativeName: 'Guinea',
		flag: '🇬🇳',
	},
	{
		iso_3166_1: 'GP',
		name: 'Guadaloupe',
		nativeName: 'Guadeloupe',
		flag: '🇬🇵',
	},
	{
		iso_3166_1: 'GQ',
		name: 'Equatorial Guinea',
		nativeName: 'Equatorial Guinea',
		flag: '🇬🇶',
	},
	{
		iso_3166_1: 'GR',
		name: 'Greece',
		nativeName: 'Greece',
		flag: '🇬🇷',
	},
	{
		iso_3166_1: 'GS',
		name: 'South Georgia and the South Sandwich Islands',
		nativeName: 'South Georgia & South Sandwich Islands',
		flag: '🇬🇸',
	},
	{
		iso_3166_1: 'GT',
		name: 'Guatemala',
		nativeName: 'Guatemala',
		flag: '🇬🇹',
	},
	{
		iso_3166_1: 'GU',
		name: 'Guam',
		nativeName: 'Guam',
		flag: '🇬🇺',
	},
	{
		iso_3166_1: 'GW',
		name: 'Guinea-Bissau',
		nativeName: 'Guinea-Bissau',
		flag: '🇬🇼',
	},
	{
		iso_3166_1: 'GY',
		name: 'Guyana',
		nativeName: 'Guyana',
		flag: '🇬🇾',
	},
	{
		iso_3166_1: 'HK',
		name: 'Hong Kong',
		nativeName: 'Hong Kong SAR China',
		flag: '🇭🇰',
	},
	{
		iso_3166_1: 'HM',
		name: 'Heard and McDonald Islands',
		nativeName: 'Heard & McDonald Islands',
		flag: '🇭🇲',
	},
	{
		iso_3166_1: 'HN',
		name: 'Honduras',
		nativeName: 'Honduras',
		flag: '🇭🇳',
	},
	{
		iso_3166_1: 'HR',
		name: 'Croatia',
		nativeName: 'Croatia',
		flag: '🇭🇷',
	},
	{
		iso_3166_1: 'HT',
		name: 'Haiti',
		nativeName: 'Haiti',
		flag: '🇭🇹',
	},
	{
		iso_3166_1: 'HU',
		name: 'Hungary',
		nativeName: 'Hungary',
		flag: '🇭🇺',
	},
	{
		iso_3166_1: 'ID',
		name: 'Indonesia',
		nativeName: 'Indonesia',
		flag: '🇮🇩',
	},
	{
		iso_3166_1: 'IE',
		name: 'Ireland',
		nativeName: 'Ireland',
		flag: '🇮🇪',
	},
	{
		iso_3166_1: 'IL',
		name: 'Israel',
		nativeName: 'Israel',
		flag: '🇮🇱',
	},
	{
		iso_3166_1: 'IN',
		name: 'India',
		nativeName: 'India',
		flag: '🇮🇳',
	},
	{
		iso_3166_1: 'IO',
		name: 'British Indian Ocean Territory',
		nativeName: 'British Indian Ocean Territory',
		flag: '🇮🇴',
	},
	{
		iso_3166_1: 'IQ',
		name: 'Iraq',
		nativeName: 'Iraq',
		flag: '🇮🇶',
	},
	{
		iso_3166_1: 'IR',
		name: 'Iran',
		nativeName: 'Iran',
		flag: '🇮🇷',
	},
	{
		iso_3166_1: 'IS',
		name: 'Iceland',
		nativeName: 'Iceland',
		flag: '🇮🇸',
	},
	{
		iso_3166_1: 'IT',
		name: 'Italy',
		nativeName: 'Italy',
		flag: '🇮🇹',
	},
	{
		iso_3166_1: 'JM',
		name: 'Jamaica',
		nativeName: 'Jamaica',
		flag: '🇯🇲',
	},
	{
		iso_3166_1: 'JO',
		name: 'Jordan',
		nativeName: 'Jordan',
		flag: '🇯🇴',
	},
	{
		iso_3166_1: 'JP',
		name: 'Japan',
		nativeName: 'Japan',
		flag: '🇯🇵',
	},
	{
		iso_3166_1: 'KE',
		name: 'Kenya',
		nativeName: 'Kenya',
		flag: '🇰🇪',
	},
	{
		iso_3166_1: 'KG',
		name: 'Kyrgyz Republic',
		nativeName: 'Kyrgyzstan',
		flag: '🇰🇬',
	},
	{
		iso_3166_1: 'KH',
		name: 'Cambodia',
		nativeName: 'Cambodia',
		flag: '🇰🇭',
	},
	{
		iso_3166_1: 'KI',
		name: 'Kiribati',
		nativeName: 'Kiribati',
		flag: '🇰🇮',
	},
	{
		iso_3166_1: 'KM',
		name: 'Comoros',
		nativeName: 'Comoros',
		flag: '🇰🇲',
	},
	{
		iso_3166_1: 'KN',
		name: 'St. Kitts and Nevis',
		nativeName: 'St. Kitts & Nevis',
		flag: '🇰🇳',
	},
	{
		iso_3166_1: 'KP',
		name: 'North Korea',
		nativeName: 'North Korea',
		flag: '🇰🇵',
	},
	{
		iso_3166_1: 'KR',
		name: 'South Korea',
		nativeName: 'South Korea',
		flag: '🇰🇷',
	},
	{
		iso_3166_1: 'KW',
		name: 'Kuwait',
		nativeName: 'Kuwait',
		flag: '🇰🇼',
	},
	{
		iso_3166_1: 'KY',
		name: 'Cayman Islands',
		nativeName: 'Cayman Islands',
		flag: '🇰🇾',
	},
	{
		iso_3166_1: 'KZ',
		name: 'Kazakhstan',
		nativeName: 'Kazakhstan',
		flag: '🇰🇿',
	},
	{
		iso_3166_1: 'LA',
		name: "Lao People's Democratic Republic",
		nativeName: 'Laos',
		flag: '🇱🇦',
	},
	{
		iso_3166_1: 'LB',
		name: 'Lebanon',
		nativeName: 'Lebanon',
		flag: '🇱🇧',
	},
	{
		iso_3166_1: 'LC',
		name: 'St. Lucia',
		nativeName: 'St. Lucia',
		flag: '🇱🇨',
	},
	{
		iso_3166_1: 'LI',
		name: 'Liechtenstein',
		nativeName: 'Liechtenstein',
		flag: '🇱🇮',
	},
	{
		iso_3166_1: 'LK',
		name: 'Sri Lanka',
		nativeName: 'Sri Lanka',
		flag: '🇱🇰',
	},
	{
		iso_3166_1: 'LR',
		name: 'Liberia',
		nativeName: 'Liberia',
		flag: '🇱🇷',
	},
	{
		iso_3166_1: 'LS',
		name: 'Lesotho',
		nativeName: 'Lesotho',
		flag: '🇱🇸',
	},
	{
		iso_3166_1: 'LT',
		name: 'Lithuania',
		nativeName: 'Lithuania',
		flag: '🇱🇹',
	},
	{
		iso_3166_1: 'LU',
		name: 'Luxembourg',
		nativeName: 'Luxembourg',
		flag: '🇱🇺',
	},
	{
		iso_3166_1: 'LV',
		name: 'Latvia',
		nativeName: 'Latvia',
		flag: '🇱🇻',
	},
	{
		iso_3166_1: 'LY',
		name: 'Libyan Arab Jamahiriya',
		nativeName: 'Libya',
		flag: '🇱🇾',
	},
	{
		iso_3166_1: 'MA',
		name: 'Morocco',
		nativeName: 'Morocco',
		flag: '🇲🇦',
	},
	{
		iso_3166_1: 'MC',
		name: 'Monaco',
		nativeName: 'Monaco',
		flag: '🇲🇨',
	},
	{
		iso_3166_1: 'MD',
		name: 'Moldova',
		nativeName: 'Moldova',
		flag: '🇲🇩',
	},
	{
		iso_3166_1: 'ME',
		name: 'Montenegro',
		nativeName: 'Montenegro',
		flag: '🇲🇪',
	},
	{
		iso_3166_1: 'MG',
		name: 'Madagascar',
		nativeName: 'Madagascar',
		flag: '🇲🇬',
	},
	{
		iso_3166_1: 'MH',
		name: 'Marshall Islands',
		nativeName: 'Marshall Islands',
		flag: '🇲🇭',
	},
	{
		iso_3166_1: 'MK',
		name: 'Macedonia',
		nativeName: 'Macedonia',
		flag: '🇲🇰',
	},
	{
		iso_3166_1: 'ML',
		name: 'Mali',
		nativeName: 'Mali',
		flag: '🇲🇱',
	},
	{
		iso_3166_1: 'MM',
		name: 'Myanmar',
		nativeName: 'Myanmar (Burma)',
		flag: '🇲🇲',
	},
	{
		iso_3166_1: 'MN',
		name: 'Mongolia',
		nativeName: 'Mongolia',
		flag: '🇲🇳',
	},
	{
		iso_3166_1: 'MO',
		name: 'Macao',
		nativeName: 'Macau SAR China',
		flag: '🇲🇴',
	},
	{
		iso_3166_1: 'MP',
		name: 'Northern Mariana Islands',
		nativeName: 'Northern Mariana Islands',
		flag: '🇲🇵',
	},
	{
		iso_3166_1: 'MQ',
		name: 'Martinique',
		nativeName: 'Martinique',
		flag: '🇲🇶',
	},
	{
		iso_3166_1: 'MR',
		name: 'Mauritania',
		nativeName: 'Mauritania',
		flag: '🇲🇷',
	},
	{
		iso_3166_1: 'MS',
		name: 'Montserrat',
		nativeName: 'Montserrat',
		flag: '🇲🇸',
	},
	{
		iso_3166_1: 'MT',
		name: 'Malta',
		nativeName: 'Malta',
		flag: '🇲🇹',
	},
	{
		iso_3166_1: 'MU',
		name: 'Mauritius',
		nativeName: 'Mauritius',
		flag: '🇲🇺',
	},
	{
		iso_3166_1: 'MV',
		name: 'Maldives',
		nativeName: 'Maldives',
		flag: '🇲🇻',
	},
	{
		iso_3166_1: 'MW',
		name: 'Malawi',
		nativeName: 'Malawi',
		flag: '🇲🇼',
	},
	{
		iso_3166_1: 'MX',
		name: 'Mexico',
		nativeName: 'Mexico',
		flag: '🇲🇽',
	},
	{
		iso_3166_1: 'MY',
		name: 'Malaysia',
		nativeName: 'Malaysia',
		flag: '🇲🇾',
	},
	{
		iso_3166_1: 'MZ',
		name: 'Mozambique',
		nativeName: 'Mozambique',
		flag: '🇲🇿',
	},
	{
		iso_3166_1: 'NA',
		name: 'Namibia',
		nativeName: 'Namibia',
		flag: '🇳🇦',
	},
	{
		iso_3166_1: 'NC',
		name: 'New Caledonia',
		nativeName: 'New Caledonia',
		flag: '🇳🇨',
	},
	{
		iso_3166_1: 'NE',
		name: 'Niger',
		nativeName: 'Niger',
		flag: '🇳🇪',
	},
	{
		iso_3166_1: 'NF',
		name: 'Norfolk Island',
		nativeName: 'Norfolk Island',
		flag: '🇳🇫',
	},
	{
		iso_3166_1: 'NG',
		name: 'Nigeria',
		nativeName: 'Nigeria',
		flag: '🇳🇬',
	},
	{
		iso_3166_1: 'NI',
		name: 'Nicaragua',
		nativeName: 'Nicaragua',
		flag: '🇳🇮',
	},
	{
		iso_3166_1: 'NL',
		name: 'Netherlands',
		nativeName: 'Netherlands',
		flag: '🇳🇱',
	},
	{
		iso_3166_1: 'NO',
		name: 'Norway',
		nativeName: 'Norway',
		flag: '🇳🇴',
	},
	{
		iso_3166_1: 'NP',
		name: 'Nepal',
		nativeName: 'Nepal',
		flag: '🇳🇵',
	},
	{
		iso_3166_1: 'NR',
		name: 'Nauru',
		nativeName: 'Nauru',
		flag: '🇳🇷',
	},
	{
		iso_3166_1: 'NU',
		name: 'Niue',
		nativeName: 'Niue',
		flag: '🇳🇺',
	},
	{
		iso_3166_1: 'NZ',
		name: 'New Zealand',
		nativeName: 'New Zealand',
		flag: '🇳🇿',
	},
	{
		iso_3166_1: 'OM',
		name: 'Oman',
		nativeName: 'Oman',
		flag: '🇴🇲',
	},
	{
		iso_3166_1: 'PA',
		name: 'Panama',
		nativeName: 'Panama',
		flag: '🇵🇦',
	},
	{
		iso_3166_1: 'PE',
		name: 'Peru',
		nativeName: 'Peru',
		flag: '🇵🇪',
	},
	{
		iso_3166_1: 'PF',
		name: 'French Polynesia',
		nativeName: 'French Polynesia',
		flag: '🇵🇫',
	},
	{
		iso_3166_1: 'PG',
		name: 'Papua New Guinea',
		nativeName: 'Papua New Guinea',
		flag: '🇵🇬',
	},
	{
		iso_3166_1: 'PH',
		name: 'Philippines',
		nativeName: 'Philippines',
		flag: '🇵🇭',
	},
	{
		iso_3166_1: 'PK',
		name: 'Pakistan',
		nativeName: 'Pakistan',
		flag: '🇵🇰',
	},
	{
		iso_3166_1: 'PL',
		name: 'Poland',
		nativeName: 'Poland',
		flag: '🇵🇱',
	},
	{
		iso_3166_1: 'PM',
		name: 'St. Pierre and Miquelon',
		nativeName: 'St. Pierre & Miquelon',
		flag: '🇵🇲',
	},
	{
		iso_3166_1: 'PN',
		name: 'Pitcairn Island',
		nativeName: 'Pitcairn Islands',
		flag: '🇵🇳',
	},
	{
		iso_3166_1: 'PR',
		name: 'Puerto Rico',
		nativeName: 'Puerto Rico',
		flag: '🇵🇷',
	},
	{
		iso_3166_1: 'PS',
		name: 'Palestinian Territory',
		nativeName: 'Palestinian Territories',
		flag: '🇵🇸',
	},
	{
		iso_3166_1: 'PT',
		name: 'Portugal',
		nativeName: 'Portugal',
		flag: '🇵🇹',
	},
	{
		iso_3166_1: 'PW',
		name: 'Palau',
		nativeName: 'Palau',
		flag: '🇵🇼',
	},
	{
		iso_3166_1: 'PY',
		name: 'Paraguay',
		nativeName: 'Paraguay',
		flag: '🇵🇾',
	},
	{
		iso_3166_1: 'QA',
		name: 'Qatar',
		nativeName: 'Qatar',
		flag: '🇶🇦',
	},
	{
		iso_3166_1: 'RE',
		name: 'Reunion',
		nativeName: 'Réunion',
		flag: '🇷🇪',
	},
	{
		iso_3166_1: 'RO',
		name: 'Romania',
		nativeName: 'Romania',
		flag: '🇷🇴',
	},
	{
		iso_3166_1: 'RS',
		name: 'Serbia',
		nativeName: 'Serbia',
		flag: '🇷🇸',
	},
	{
		iso_3166_1: 'RU',
		name: 'Russia',
		nativeName: 'Russia',
		flag: '🇷🇺',
	},
	{
		iso_3166_1: 'RW',
		name: 'Rwanda',
		nativeName: 'Rwanda',
		flag: '🇷🇼',
	},
	{
		iso_3166_1: 'SA',
		name: 'Saudi Arabia',
		nativeName: 'Saudi Arabia',
		flag: '🇸🇦',
	},
	{
		iso_3166_1: 'SB',
		name: 'Solomon Islands',
		nativeName: 'Solomon Islands',
		flag: '🇸🇧',
	},
	{
		iso_3166_1: 'SC',
		name: 'Seychelles',
		nativeName: 'Seychelles',
		flag: '🇸🇨',
	},
	{
		iso_3166_1: 'SD',
		name: 'Sudan',
		nativeName: 'Sudan',
		flag: '🇸🇩',
	},
	{
		iso_3166_1: 'SE',
		name: 'Sweden',
		nativeName: 'Sweden',
		flag: '🇸🇪',
	},
	{
		iso_3166_1: 'SG',
		name: 'Singapore',
		nativeName: 'Singapore',
		flag: '🇸🇬',
	},
	{
		iso_3166_1: 'SH',
		name: 'St. Helena',
		nativeName: 'St. Helena',
		flag: '🇸🇭',
	},
	{
		iso_3166_1: 'SI',
		name: 'Slovenia',
		nativeName: 'Slovenia',
		flag: '🇸🇮',
	},
	{
		iso_3166_1: 'SJ',
		name: 'Svalbard & Jan Mayen Islands',
		nativeName: 'Svalbard & Jan Mayen',
		flag: '🇸🇯',
	},
	{
		iso_3166_1: 'SK',
		name: 'Slovakia',
		nativeName: 'Slovakia',
		flag: '🇸🇰',
	},
	{
		iso_3166_1: 'SL',
		name: 'Sierra Leone',
		nativeName: 'Sierra Leone',
		flag: '🇸🇱',
	},
	{
		iso_3166_1: 'SM',
		name: 'San Marino',
		nativeName: 'San Marino',
		flag: '🇸🇲',
	},
	{
		iso_3166_1: 'SN',
		name: 'Senegal',
		nativeName: 'Senegal',
		flag: '🇸🇳',
	},
	{
		iso_3166_1: 'SO',
		name: 'Somalia',
		nativeName: 'Somalia',
		flag: '🇸🇴',
	},
	{
		iso_3166_1: 'SR',
		name: 'Suriname',
		nativeName: 'Suriname',
		flag: '🇸🇷',
	},
	{
		iso_3166_1: 'SS',
		name: 'South Sudan',
		nativeName: 'South Sudan',
		flag: '🇸🇸',
	},
	{
		iso_3166_1: 'ST',
		name: 'Sao Tome and Principe',
		nativeName: 'São Tomé & Príncipe',
		flag: '🇸🇹',
	},
	{
		iso_3166_1: 'SU',
		name: 'Soviet Union',
		nativeName: 'Soviet Union',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'SV',
		name: 'El Salvador',
		nativeName: 'El Salvador',
		flag: '🇸🇻',
	},
	{
		iso_3166_1: 'SY',
		name: 'Syrian Arab Republic',
		nativeName: 'Syria',
		flag: '🇸🇾',
	},
	{
		iso_3166_1: 'SZ',
		name: 'Swaziland',
		nativeName: 'Eswatini (Swaziland)',
		flag: '🇸🇿',
	},
	{
		iso_3166_1: 'TC',
		name: 'Turks and Caicos Islands',
		nativeName: 'Turks & Caicos Islands',
		flag: '🇹🇨',
	},
	{
		iso_3166_1: 'TD',
		name: 'Chad',
		nativeName: 'Chad',
		flag: '🇹🇩',
	},
	{
		iso_3166_1: 'TF',
		name: 'French Southern Territories',
		nativeName: 'French Southern Territories',
		flag: '🇹🇫',
	},
	{
		iso_3166_1: 'TG',
		name: 'Togo',
		nativeName: 'Togo',
		flag: '🇹🇬',
	},
	{
		iso_3166_1: 'TH',
		name: 'Thailand',
		nativeName: 'Thailand',
		flag: '🇹🇭',
	},
	{
		iso_3166_1: 'TJ',
		name: 'Tajikistan',
		nativeName: 'Tajikistan',
		flag: '🇹🇯',
	},
	{
		iso_3166_1: 'TK',
		name: 'Tokelau',
		nativeName: 'Tokelau',
		flag: '🇹🇰',
	},
	{
		iso_3166_1: 'TL',
		name: 'Timor-Leste',
		nativeName: 'Timor-Leste',
		flag: '🇹🇱',
	},
	{
		iso_3166_1: 'TM',
		name: 'Turkmenistan',
		nativeName: 'Turkmenistan',
		flag: '🇹🇲',
	},
	{
		iso_3166_1: 'TN',
		name: 'Tunisia',
		nativeName: 'Tunisia',
		flag: '🇹🇳',
	},
	{
		iso_3166_1: 'TO',
		name: 'Tonga',
		nativeName: 'Tonga',
		flag: '🇹🇴',
	},
	{
		iso_3166_1: 'TP',
		name: 'East Timor',
		nativeName: 'East Timor',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'TR',
		name: 'Turkey',
		nativeName: 'Turkey',
		flag: '🇹🇷',
	},
	{
		iso_3166_1: 'TT',
		name: 'Trinidad and Tobago',
		nativeName: 'Trinidad & Tobago',
		flag: '🇹🇹',
	},
	{
		iso_3166_1: 'TV',
		name: 'Tuvalu',
		nativeName: 'Tuvalu',
		flag: '🇹🇻',
	},
	{
		iso_3166_1: 'TW',
		name: 'Taiwan',
		nativeName: 'Taiwan',
		flag: '🇹🇼',
	},
	{
		iso_3166_1: 'TZ',
		name: 'Tanzania',
		nativeName: 'Tanzania',
		flag: '🇹🇿',
	},
	{
		iso_3166_1: 'UA',
		name: 'Ukraine',
		nativeName: 'Ukraine',
		flag: '🇺🇦',
	},
	{
		iso_3166_1: 'UG',
		name: 'Uganda',
		nativeName: 'Uganda',
		flag: '🇺🇬',
	},
	{
		iso_3166_1: 'UM',
		name: 'United States Minor Outlying Islands',
		nativeName: 'U.S. Outlying Islands',
		flag: '🇺🇲',
	},
	{
		iso_3166_1: 'US',
		name: 'United States of America',
		nativeName: 'United States',
		flag: '🇺🇸',
	},
	{
		iso_3166_1: 'UY',
		name: 'Uruguay',
		nativeName: 'Uruguay',
		flag: '🇺🇾',
	},
	{
		iso_3166_1: 'UZ',
		name: 'Uzbekistan',
		nativeName: 'Uzbekistan',
		flag: '🇺🇿',
	},
	{
		iso_3166_1: 'VA',
		name: 'Holy See',
		nativeName: 'Vatican City',
		flag: '🇻🇦',
	},
	{
		iso_3166_1: 'VC',
		name: 'St. Vincent and the Grenadines',
		nativeName: 'St. Vincent & Grenadines',
		flag: '🇻🇨',
	},
	{
		iso_3166_1: 'VE',
		name: 'Venezuela',
		nativeName: 'Venezuela',
		flag: '🇻🇪',
	},
	{
		iso_3166_1: 'VG',
		name: 'British Virgin Islands',
		nativeName: 'British Virgin Islands',
		flag: '🇻🇬',
	},
	{
		iso_3166_1: 'VI',
		name: 'US Virgin Islands',
		nativeName: 'U.S. Virgin Islands',
		flag: '🇻🇮',
	},
	{
		iso_3166_1: 'VN',
		name: 'Vietnam',
		nativeName: 'Vietnam',
		flag: '🇻🇳',
	},
	{
		iso_3166_1: 'VU',
		name: 'Vanuatu',
		nativeName: 'Vanuatu',
		flag: '🇻🇺',
	},
	{
		iso_3166_1: 'WF',
		name: 'Wallis and Futuna Islands',
		nativeName: 'Wallis & Futuna',
		flag: '🇼🇫',
	},
	{
		iso_3166_1: 'WS',
		name: 'Samoa',
		nativeName: 'Samoa',
		flag: '🇼🇸',
	},
	{
		iso_3166_1: 'XC',
		name: 'Czechoslovakia',
		nativeName: 'Czechoslovakia',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'XG',
		name: 'East Germany',
		nativeName: 'East Germany',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'XI',
		name: 'Northern Ireland',
		nativeName: 'Northern Ireland',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'XK',
		name: 'Kosovo',
		nativeName: 'Kosovo',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'YE',
		name: 'Yemen',
		nativeName: 'Yemen',
		flag: '🇾🇪',
	},
	{
		iso_3166_1: 'YT',
		name: 'Mayotte',
		nativeName: 'Mayotte',
		flag: '🇾🇹',
	},
	{
		iso_3166_1: 'YU',
		name: 'Yugoslavia',
		nativeName: 'Yugoslavia',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'ZA',
		name: 'South Africa',
		nativeName: 'South Africa',
		flag: '🇿🇦',
	},
	{
		iso_3166_1: 'ZM',
		name: 'Zambia',
		nativeName: 'Zambia',
		flag: '🇿🇲',
	},
	{
		iso_3166_1: 'ZR',
		name: 'Zaire',
		nativeName: 'Zaire',
		flag: '🏳️',
	},
	{
		iso_3166_1: 'ZW',
		name: 'Zimbabwe',
		nativeName: 'Zimbabwe',
		flag: '🇿🇼',
	},
]

export const LANGUAGES = [
	{
		iso_639_1: 'bi',
		name: 'Bislama',
		nativeName: '',
	},
	{
		iso_639_1: 'cs',
		name: 'Czech',
		nativeName: 'Český',
	},
	{
		iso_639_1: 'ba',
		name: 'Bashkir',
		nativeName: '',
	},
	{
		iso_639_1: 'ae',
		name: 'Avestan',
		nativeName: '',
	},
	{
		iso_639_1: 'av',
		name: 'Avaric',
		nativeName: '',
	},
	{
		iso_639_1: 'de',
		name: 'German',
		nativeName: 'Deutsch',
	},
	{
		iso_639_1: 'mt',
		name: 'Maltese',
		nativeName: 'Malti',
	},
	{
		iso_639_1: 'om',
		name: 'Oromo',
		nativeName: '',
	},
	{
		iso_639_1: 'rm',
		name: 'Raeto-Romance',
		nativeName: '',
	},
	{
		iso_639_1: 'so',
		name: 'Somali',
		nativeName: 'Somali',
	},
	{
		iso_639_1: 'ts',
		name: 'Tsonga',
		nativeName: '',
	},
	{
		iso_639_1: 'vi',
		name: 'Vietnamese',
		nativeName: 'Tiếng Việt',
	},
	{
		iso_639_1: 'gn',
		name: 'Guarani',
		nativeName: '',
	},
	{
		iso_639_1: 'ig',
		name: 'Igbo',
		nativeName: '',
	},
	{
		iso_639_1: 'it',
		name: 'Italian',
		nativeName: 'Italiano',
	},
	{
		iso_639_1: 'ki',
		name: 'Kikuyu',
		nativeName: '',
	},
	{
		iso_639_1: 'ku',
		name: 'Kurdish',
		nativeName: '',
	},
	{
		iso_639_1: 'la',
		name: 'Latin',
		nativeName: 'Latin',
	},
	{
		iso_639_1: 'ln',
		name: 'Lingala',
		nativeName: '',
	},
	{
		iso_639_1: 'lb',
		name: 'Letzeburgesch',
		nativeName: '',
	},
	{
		iso_639_1: 'ny',
		name: 'Chichewa; Nyanja',
		nativeName: '',
	},
	{
		iso_639_1: 'pl',
		name: 'Polish',
		nativeName: 'Polski',
	},
	{
		iso_639_1: 'si',
		name: 'Sinhalese',
		nativeName: 'සිංහල',
	},
	{
		iso_639_1: 'to',
		name: 'Tonga',
		nativeName: '',
	},
	{
		iso_639_1: 'az',
		name: 'Azerbaijani',
		nativeName: 'Azərbaycan',
	},
	{
		iso_639_1: 'ce',
		name: 'Chechen',
		nativeName: '',
	},
	{
		iso_639_1: 'cu',
		name: 'Slavic',
		nativeName: '',
	},
	{
		iso_639_1: 'da',
		name: 'Danish',
		nativeName: 'Dansk',
	},
	{
		iso_639_1: 'hz',
		name: 'Herero',
		nativeName: '',
	},
	{
		iso_639_1: 'ie',
		name: 'Interlingue',
		nativeName: '',
	},
	{
		iso_639_1: 'rw',
		name: 'Kinyarwanda',
		nativeName: 'Kinyarwanda',
	},
	{
		iso_639_1: 'mi',
		name: 'Maori',
		nativeName: '',
	},
	{
		iso_639_1: 'no',
		name: 'Norwegian',
		nativeName: 'Norsk',
	},
	{
		iso_639_1: 'pi',
		name: 'Pali',
		nativeName: '',
	},
	{
		iso_639_1: 'sk',
		name: 'Slovak',
		nativeName: 'Slovenčina',
	},
	{
		iso_639_1: 'se',
		name: 'Northern Sami',
		nativeName: '',
	},
	{
		iso_639_1: 'sm',
		name: 'Samoan',
		nativeName: '',
	},
	{
		iso_639_1: 'uk',
		name: 'Ukrainian',
		nativeName: 'Український',
	},
	{
		iso_639_1: 'en',
		name: 'English',
		nativeName: 'English',
	},
	{
		iso_639_1: 'ay',
		name: 'Aymara',
		nativeName: '',
	},
	{
		iso_639_1: 'ca',
		name: 'Catalan',
		nativeName: 'Català',
	},
	{
		iso_639_1: 'eo',
		name: 'Esperanto',
		nativeName: 'Esperanto',
	},
	{
		iso_639_1: 'ha',
		name: 'Hausa',
		nativeName: 'Hausa',
	},
	{
		iso_639_1: 'ho',
		name: 'Hiri Motu',
		nativeName: '',
	},
	{
		iso_639_1: 'hu',
		name: 'Hungarian',
		nativeName: 'Magyar',
	},
	{
		iso_639_1: 'io',
		name: 'Ido',
		nativeName: '',
	},
	{
		iso_639_1: 'ii',
		name: 'Yi',
		nativeName: '',
	},
	{
		iso_639_1: 'kn',
		name: 'Kannada',
		nativeName: '?????',
	},
	{
		iso_639_1: 'kv',
		name: 'Komi',
		nativeName: '',
	},
	{
		iso_639_1: 'li',
		name: 'Limburgish',
		nativeName: '',
	},
	{
		iso_639_1: 'oj',
		name: 'Ojibwa',
		nativeName: '',
	},
	{
		iso_639_1: 'ru',
		name: 'Russian',
		nativeName: 'Pусский',
	},
	{
		iso_639_1: 'sr',
		name: 'Serbian',
		nativeName: 'Srpski',
	},
	{
		iso_639_1: 'sv',
		name: 'Swedish',
		nativeName: 'svenska',
	},
	{
		iso_639_1: 'ty',
		name: 'Tahitian',
		nativeName: '',
	},
	{
		iso_639_1: 'zu',
		name: 'Zulu',
		nativeName: 'isiZulu',
	},
	{
		iso_639_1: 'ka',
		name: 'Georgian',
		nativeName: 'ქართული',
	},
	{
		iso_639_1: 'ch',
		name: 'Chamorro',
		nativeName: "Finu' Chamorro",
	},
	{
		iso_639_1: 'be',
		name: 'Belarusian',
		nativeName: 'беларуская мова',
	},
	{
		iso_639_1: 'br',
		name: 'Breton',
		nativeName: '',
	},
	{
		iso_639_1: 'kw',
		name: 'Cornish',
		nativeName: '',
	},
	{
		iso_639_1: 'fi',
		name: 'Finnish',
		nativeName: 'suomi',
	},
	{
		iso_639_1: 'sh',
		name: 'Serbo-Croatian',
		nativeName: '',
	},
	{
		iso_639_1: 'nn',
		name: 'Norwegian Nynorsk',
		nativeName: '',
	},
	{
		iso_639_1: 'tt',
		name: 'Tatar',
		nativeName: '',
	},
	{
		iso_639_1: 'tg',
		name: 'Tajik',
		nativeName: '',
	},
	{
		iso_639_1: 'vo',
		name: 'Volapük',
		nativeName: '',
	},
	{
		iso_639_1: 'ps',
		name: 'Pushto',
		nativeName: 'پښتو',
	},
	{
		iso_639_1: 'mk',
		name: 'Macedonian',
		nativeName: '',
	},
	{
		iso_639_1: 'fr',
		name: 'French',
		nativeName: 'Français',
	},
	{
		iso_639_1: 'bm',
		name: 'Bambara',
		nativeName: 'Bamanankan',
	},
	{
		iso_639_1: 'eu',
		name: 'Basque',
		nativeName: 'euskera',
	},
	{
		iso_639_1: 'fj',
		name: 'Fijian',
		nativeName: '',
	},
	{
		iso_639_1: 'id',
		name: 'Indonesian',
		nativeName: 'Bahasa indonesia',
	},
	{
		iso_639_1: 'mg',
		name: 'Malagasy',
		nativeName: '',
	},
	{
		iso_639_1: 'na',
		name: 'Nauru',
		nativeName: '',
	},
	{
		iso_639_1: 'xx',
		name: 'No Language',
		nativeName: 'No Language',
	},
	{
		iso_639_1: 'qu',
		name: 'Quechua',
		nativeName: '',
	},
	{
		iso_639_1: 'sq',
		name: 'Albanian',
		nativeName: 'shqip',
	},
	{
		iso_639_1: 'ti',
		name: 'Tigrinya',
		nativeName: '',
	},
	{
		iso_639_1: 'tw',
		name: 'Twi',
		nativeName: '',
	},
	{
		iso_639_1: 'wa',
		name: 'Walloon',
		nativeName: '',
	},
	{
		iso_639_1: 'ab',
		name: 'Abkhazian',
		nativeName: '',
	},
	{
		iso_639_1: 'bs',
		name: 'Bosnian',
		nativeName: 'Bosanski',
	},
	{
		iso_639_1: 'af',
		name: 'Afrikaans',
		nativeName: 'Afrikaans',
	},
	{
		iso_639_1: 'an',
		name: 'Aragonese',
		nativeName: '',
	},
	{
		iso_639_1: 'fy',
		name: 'Frisian',
		nativeName: '',
	},
	{
		iso_639_1: 'gu',
		name: 'Gujarati',
		nativeName: '',
	},
	{
		iso_639_1: 'ik',
		name: 'Inupiaq',
		nativeName: '',
	},
	{
		iso_639_1: 'ja',
		name: 'Japanese',
		nativeName: '日本語',
	},
	{
		iso_639_1: 'ko',
		name: 'Korean',
		nativeName: '한국어/조선말',
	},
	{
		iso_639_1: 'lg',
		name: 'Ganda',
		nativeName: '',
	},
	{
		iso_639_1: 'nl',
		name: 'Dutch',
		nativeName: 'Nederlands',
	},
	{
		iso_639_1: 'os',
		name: 'Ossetian; Ossetic',
		nativeName: '',
	},
	{
		iso_639_1: 'el',
		name: 'Greek',
		nativeName: 'ελληνικά',
	},
	{
		iso_639_1: 'bn',
		name: 'Bengali',
		nativeName: 'বাংলা',
	},
	{
		iso_639_1: 'cr',
		name: 'Cree',
		nativeName: '',
	},
	{
		iso_639_1: 'km',
		name: 'Khmer',
		nativeName: '',
	},
	{
		iso_639_1: 'lo',
		name: 'Lao',
		nativeName: '',
	},
	{
		iso_639_1: 'nd',
		name: 'Ndebele',
		nativeName: '',
	},
	{
		iso_639_1: 'ne',
		name: 'Nepali',
		nativeName: '',
	},
	{
		iso_639_1: 'sc',
		name: 'Sardinian',
		nativeName: '',
	},
	{
		iso_639_1: 'sw',
		name: 'Swahili',
		nativeName: 'Kiswahili',
	},
	{
		iso_639_1: 'tl',
		name: 'Tagalog',
		nativeName: '',
	},
	{
		iso_639_1: 'ur',
		name: 'Urdu',
		nativeName: 'اردو',
	},
	{
		iso_639_1: 'ee',
		name: 'Ewe',
		nativeName: 'Èʋegbe',
	},
	{
		iso_639_1: 'aa',
		name: 'Afar',
		nativeName: '',
	},
	{
		iso_639_1: 'co',
		name: 'Corsican',
		nativeName: '',
	},
	{
		iso_639_1: 'et',
		name: 'Estonian',
		nativeName: 'Eesti',
	},
	{
		iso_639_1: 'is',
		name: 'Icelandic',
		nativeName: 'Íslenska',
	},
	{
		iso_639_1: 'ks',
		name: 'Kashmiri',
		nativeName: '',
	},
	{
		iso_639_1: 'kr',
		name: 'Kanuri',
		nativeName: '',
	},
	{
		iso_639_1: 'ky',
		name: 'Kirghiz',
		nativeName: '??????',
	},
	{
		iso_639_1: 'kj',
		name: 'Kuanyama',
		nativeName: '',
	},
	{
		iso_639_1: 'or',
		name: 'Oriya',
		nativeName: '',
	},
	{
		iso_639_1: 'wo',
		name: 'Wolof',
		nativeName: 'Wolof',
	},
	{
		iso_639_1: 'za',
		name: 'Zhuang',
		nativeName: '',
	},
	{
		iso_639_1: 'ar',
		name: 'Arabic',
		nativeName: 'العربية',
	},
	{
		iso_639_1: 'cv',
		name: 'Chuvash',
		nativeName: '',
	},
	{
		iso_639_1: 'fo',
		name: 'Faroese',
		nativeName: '',
	},
	{
		iso_639_1: 'hr',
		name: 'Croatian',
		nativeName: 'Hrvatski',
	},
	{
		iso_639_1: 'ms',
		name: 'Malay',
		nativeName: 'Bahasa melayu',
	},
	{
		iso_639_1: 'nb',
		name: 'Norwegian Bokmål',
		nativeName: 'Bokmål',
	},
	{
		iso_639_1: 'rn',
		name: 'Rundi',
		nativeName: 'Kirundi',
	},
	{
		iso_639_1: 'sn',
		name: 'Shona',
		nativeName: '',
	},
	{
		iso_639_1: 'st',
		name: 'Sotho',
		nativeName: '',
	},
	{
		iso_639_1: 'tr',
		name: 'Turkish',
		nativeName: 'Türkçe',
	},
	{
		iso_639_1: 'am',
		name: 'Amharic',
		nativeName: '',
	},
	{
		iso_639_1: 'fa',
		name: 'Persian',
		nativeName: 'فارسی',
	},
	{
		iso_639_1: 'hy',
		name: 'Armenian',
		nativeName: '',
	},
	{
		iso_639_1: 'pa',
		name: 'Punjabi',
		nativeName: 'ਪੰਜਾਬੀ',
	},
	{
		iso_639_1: 'as',
		name: 'Assamese',
		nativeName: '',
	},
	{
		iso_639_1: 'ia',
		name: 'Interlingua',
		nativeName: '',
	},
	{
		iso_639_1: 'lv',
		name: 'Latvian',
		nativeName: 'Latviešu',
	},
	{
		iso_639_1: 'lu',
		name: 'Luba-Katanga',
		nativeName: '',
	},
	{
		iso_639_1: 'mr',
		name: 'Marathi',
		nativeName: '',
	},
	{
		iso_639_1: 'mn',
		name: 'Mongolian',
		nativeName: '',
	},
	{
		iso_639_1: 'pt',
		name: 'Portuguese',
		nativeName: 'Português',
	},
	{
		iso_639_1: 'th',
		name: 'Thai',
		nativeName: 'ภาษาไทย',
	},
	{
		iso_639_1: 'tk',
		name: 'Turkmen',
		nativeName: '',
	},
	{
		iso_639_1: 've',
		name: 'Venda',
		nativeName: '',
	},
	{
		iso_639_1: 'dv',
		name: 'Divehi',
		nativeName: '',
	},
	{
		iso_639_1: 'gv',
		name: 'Manx',
		nativeName: '',
	},
	{
		iso_639_1: 'kl',
		name: 'Kalaallisut',
		nativeName: '',
	},
	{
		iso_639_1: 'kk',
		name: 'Kazakh',
		nativeName: 'қазақ',
	},
	{
		iso_639_1: 'lt',
		name: 'Lithuanian',
		nativeName: 'Lietuvių',
	},
	{
		iso_639_1: 'my',
		name: 'Burmese',
		nativeName: '',
	},
	{
		iso_639_1: 'sl',
		name: 'Slovenian',
		nativeName: 'Slovenščina',
	},
	{
		iso_639_1: 'sd',
		name: 'Sindhi',
		nativeName: '',
	},
	{
		iso_639_1: 'cn',
		name: 'Cantonese',
		nativeName: '广州话 / 廣州話',
	},
	{
		iso_639_1: 'hi',
		name: 'Hindi',
		nativeName: 'हिन्दी',
	},
	{
		iso_639_1: 'cy',
		name: 'Welsh',
		nativeName: 'Cymraeg',
	},
	{
		iso_639_1: 'ht',
		name: 'Haitian; Haitian Creole',
		nativeName: '',
	},
	{
		iso_639_1: 'iu',
		name: 'Inuktitut',
		nativeName: '',
	},
	{
		iso_639_1: 'jv',
		name: 'Javanese',
		nativeName: '',
	},
	{
		iso_639_1: 'mh',
		name: 'Marshall',
		nativeName: '',
	},
	{
		iso_639_1: 'sa',
		name: 'Sanskrit',
		nativeName: '',
	},
	{
		iso_639_1: 'ss',
		name: 'Swati',
		nativeName: '',
	},
	{
		iso_639_1: 'te',
		name: 'Telugu',
		nativeName: 'తెలుగు',
	},
	{
		iso_639_1: 'kg',
		name: 'Kongo',
		nativeName: '',
	},
	{
		iso_639_1: 'ml',
		name: 'Malayalam',
		nativeName: '',
	},
	{
		iso_639_1: 'uz',
		name: 'Uzbek',
		nativeName: 'ozbek',
	},
	{
		iso_639_1: 'sg',
		name: 'Sango',
		nativeName: '',
	},
	{
		iso_639_1: 'xh',
		name: 'Xhosa',
		nativeName: '',
	},
	{
		iso_639_1: 'es',
		name: 'Spanish',
		nativeName: 'Español',
	},
	{
		iso_639_1: 'su',
		name: 'Sundanese',
		nativeName: '',
	},
	{
		iso_639_1: 'ug',
		name: 'Uighur',
		nativeName: '',
	},
	{
		iso_639_1: 'yi',
		name: 'Yiddish',
		nativeName: '',
	},
	{
		iso_639_1: 'yo',
		name: 'Yoruba',
		nativeName: 'Èdè Yorùbá',
	},
	{
		iso_639_1: 'zh',
		name: 'Mandarin',
		nativeName: '普通话',
	},
	{
		iso_639_1: 'he',
		name: 'Hebrew',
		nativeName: 'עִבְרִית',
	},
	{
		iso_639_1: 'bo',
		name: 'Tibetan',
		nativeName: '',
	},
	{
		iso_639_1: 'ak',
		name: 'Akan',
		nativeName: '',
	},
	{
		iso_639_1: 'mo',
		name: 'Moldavian',
		nativeName: '',
	},
	{
		iso_639_1: 'ng',
		name: 'Ndonga',
		nativeName: '',
	},
	{
		iso_639_1: 'dz',
		name: 'Dzongkha',
		nativeName: '',
	},
	{
		iso_639_1: 'ff',
		name: 'Fulah',
		nativeName: 'Fulfulde',
	},
	{
		iso_639_1: 'gd',
		name: 'Gaelic',
		nativeName: '',
	},
	{
		iso_639_1: 'ga',
		name: 'Irish',
		nativeName: 'Gaeilge',
	},
	{
		iso_639_1: 'gl',
		name: 'Galician',
		nativeName: 'Galego',
	},
	{
		iso_639_1: 'nv',
		name: 'Navajo',
		nativeName: '',
	},
	{
		iso_639_1: 'oc',
		name: 'Occitan',
		nativeName: '',
	},
	{
		iso_639_1: 'ro',
		name: 'Romanian',
		nativeName: 'Română',
	},
	{
		iso_639_1: 'ta',
		name: 'Tamil',
		nativeName: 'தமிழ்',
	},
	{
		iso_639_1: 'tn',
		name: 'Tswana',
		nativeName: '',
	},
	{
		iso_639_1: 'bg',
		name: 'Bulgarian',
		nativeName: 'български език',
	},
]

export const AGE_RATINGS = [
	{ value: 'U', label: 'U' },
	{ value: 'PG', label: 'PG' },
	{ value: '12', label: '12' },
	{ value: '12A', label: '12A' },
	{ value: '15', label: '15' },
	{ value: '18', label: '18' },
]

export const STATUSES = [
	{ name: 'Rumoured', icon: 'question-mark' },
	{ name: 'Planned', icon: 'reader' },
	{ name: 'In Production', icon: 'scissors' },
	{ name: 'Post Production', icon: 'magic-wand' },
	{ name: 'Released', icon: 'check' },
	{ name: 'Cancelled', icon: 'cross-1' },
]

type Role = {
	department: string
	jobs: string[]
}

export function getAllJobs() {
	const jobs: Role['jobs'] = []
	ROLES.forEach((department) => {
		department.jobs.forEach((job) => {
			jobs.push(job)
		})
	})
	return jobs
}

export const ROLES: Role[] = [
	{
		department: 'Acting',
		jobs: ['Actor', 'Stunt Double', 'Voice', 'Cameo', 'Special Guest'],
	},
	{
		department: 'Camera',
		jobs: [
			'Director of Photography',
			'Underwater Camera',
			'Camera Operator',
			'Still Photographer',
			'Camera Department Manager',
			'Camera Supervisor',
			'Camera Technician',
			'Other',
			'Grip',
			'Steadicam Operator',
			'Additional Camera',
			'Camera Intern',
			'Additional Photography',
			'Helicopter Camera',
			'First Assistant Camera',
			'Additional Still Photographer',
			'Aerial Camera',
			'Aerial Camera Technician',
			'Aerial Director of Photography',
			'Camera Loader',
			'Dolly Grip',
			'Epk Camera Operator',
			'Key Grip',
			'Russian Arm Operator',
			'Second Unit Director of Photography',
			'Ultimate Arm Operator',
			'Underwater Director of Photography',
			'"A" Camera Operator',
			'"B" Camera Operator',
			'"C" Camera Operator',
			'"D" Camera Operator',
			'Additional Director of Photography',
			'Additional First Assistant Camera',
			'Additional Grip',
			'Additional Key Grip',
			'Additional Second Assistant Camera',
			'Additional Set Photographer',
			'Additional Underwater Photography',
			'Assistant Camera',
			'Assistant Grip',
			'Best Boy Grip',
			'BTS Footage',
			'BTS Photographer',
			'BTS Videographer',
			'Camera Car',
			'Camera Department Production Assistant',
			'Camera Production Assistant',
			'Camera Trainee',
			'Camera Truck',
			'Clapper Loader',
			'Data Wrangler',
			'Digital Imaging Technician',
			'Drone Cinematographer',
			'Drone Pilot',
			'Epk Director',
			'Epk Producer',
			'First Assistant "A" Camera',
			'First Assistant "B" Camera',
			'First Assistant "C" Camera',
			'First Assistant "D" Camera',
			'First Company Grip',
			'Focus Puller',
			'Head of Layout',
			'Jimmy Jib Operator',
			'Libra Head Technician',
			'Phantom Operator',
			'Red Technician',
			'Second Assistant "A" Camera',
			'Second Assistant "B" Camera',
			'Second Assistant "C" Camera',
			'Second Assistant "D" Camera',
			'Second Assistant Camera',
			'Second Company Grip',
			'Set Photographer',
			'Third Assistant "A" Camera',
			'Third Assistant "B" Camera',
			'Third Assistant "C" Camera',
			'Third Assistant "D" Camera',
			'Third Assistant Camera',
			'Underwater Epk Photographer',
			'Underwater Stills Photographer',
			'Videojournalist',
			'Video Report',
		],
	},
	{
		department: 'Directing',
		jobs: [
			'Director',
			'Script Supervisor',
			'Other',
			'Layout',
			'Script Coordinator',
			'Special Guest Director',
			'Assistant Director',
			'Co-Director',
			'Continuity',
			'First Assistant Director',
			'Second Assistant Director',
			'Third Assistant Director',
			'Action Director',
			'Additional Second Assistant Director',
			'Additional Third Assistant Director',
			'Assistant Director Trainee',
			'Crowd Assistant Director',
			'Field Director',
			'First Assistant Director (Prep)',
			'First Assistant Director Trainee',
			'Insert Unit Director',
			'Insert Unit First Assistant Director',
			'Second Assistant Director Trainee',
			'Second Second Assistant Director',
			'Second Unit Director',
			'Second Unit First Assistant Director',
			'Series Director',
			'Stage Director',
		],
	},
	{
		department: 'Writing',
		jobs: [
			'Screenplay',
			'Author',
			'Novel',
			'Characters',
			'Theatre Play',
			'Adaptation',
			'Dialogue',
			'Writer',
			'Other',
			'Storyboard',
			'Original Story',
			'Scenario Writer',
			'Screenstory',
			'Musical',
			'Idea',
			'Story',
			'Creative Producer',
			'Teleplay',
			'Opera',
			'Co-Writer',
			'Book',
			'Comic Book',
			'Short Story',
			'Series Composition',
			'Script Editor',
			'Script Consultant',
			'Story Editor',
			'Executive Story Editor',
			'Graphic Novel',
			'Head of Story',
			'Junior Story Editor',
			'Lyricist',
			'Original Concept',
			'Original Film Writer',
			'Original Series Creator',
			'Senior Story Editor',
			'Staff Writer',
			'Story Artist',
			'Story Consultant',
			'Story Coordinator',
			'Story Developer',
			'Story Manager',
			'Story Supervisor',
			"Writers' Assistant",
			"Writers' Production",
		],
	},
	{
		department: 'Art',
		jobs: [
			'Production Design',
			'Art Direction',
			'Set Decoration',
			'Set Designer',
			'Conceptual Design',
			'Interior Designer',
			'Settings',
			'Assistant Art Director',
			'Art Department Coordinator',
			'Assistant Property Master',
			'Other',
			'Art Department Manager',
			'Sculptor',
			'Art Department Assistant',
			'Background Designer',
			'Co-Art Director',
			'Set Decoration Buyer',
			'Production Illustrator',
			'Standby Painter',
			'Property Master',
			'Location Scout',
			'Supervising Art Director',
			'Leadman',
			'Greensman',
			'Gun Wrangler',
			'Construction Coordinator',
			'Construction Foreman',
			'Lead Painter',
			'Sign Painter',
			'Painter',
			'Assistant Set Dresser',
			'Conceptual Illustrator',
			'Draughtsman',
			'Lead Set Dresser',
			'Prop Designer',
			'Set Decorating Coordinator',
			'Set Dresser',
			'Storyboard Designer',
			'Title Designer',
			'Additional Construction',
			'Additional Construction Grip',
			'Additional Key Construction Grip',
			'Additional Set Dresser',
			'Additional Storyboarding',
			'Art Department Trainee',
			'Art Designer',
			'Art Direction Intern',
			'Assistant Decorator',
			'Assistant Director of Photography',
			'Assistant Production Design',
			'Assistant Set Decoration Buyer',
			'Assistant Set Decoration',
			'Assistant Set Designer',
			'Assistant Set Propsman',
			'Concept Artist',
			'Construction Buyer',
			'Construction Grip',
			'Construction Manager',
			'Creative Director',
			'Daily Grip',
			'Decorator',
			'Digital Storyboarding',
			'Dressing Prop',
			'First Assistant Art Direction',
			'First Assistant Property Master',
			'Graphic Designer',
			'Head Carpenter',
			'Head Decorator',
			'Head Designer',
			'Head Greensman',
			'Helping Hand',
			'Key Carpenter',
			'Key Construction Grip',
			'Key Set Painter',
			'Main Title Designer',
			'On Set Computer Graphics',
			'On Set Key Props',
			'On Set Props',
			'Opening Title Sequence',
			'Original Series Design',
			'Paint Coordinator',
			'Petty Cash Buyer',
			'Property Builder',
			'Property Buyer',
			'Property Graphic Designer',
			'Props',
			'Runner Art Department',
			'Second Assistant Art Director',
			'Set Dressing Buyer',
			'Set Painter',
			'Set Propsman',
			'Set Supervisor',
			'Set Buyer',
			'Shop Electric',
			'Special Props',
			'Standby Art Director',
			'Standby Carpenter',
			'Standby Property Master',
			'Storyboard Artist',
			'Storyboard Assistant',
			'Supervising Carpenter',
			'Swing',
			'Textile Artist',
			'Title Illustration',
			'Web Designer',
		],
	},
	{
		department: 'Production',
		jobs: [
			'Producer',
			'Executive Producer',
			'Casting',
			'Production Manager',
			'Unit Production Manager',
			'Line Producer',
			'Location Manager',
			'Other',
			'Production Supervisor',
			'Production Accountant',
			'Production Office Coordinator',
			'Finance',
			'Executive Consultant',
			'Character Technical Supervisor',
			'Development Manager',
			'Administration',
			'Executive In Charge Of Post Production',
			'Production Director',
			'Executive In Charge Of Production',
			'Publicist',
			'Associate Producer',
			'Co-Producer',
			'Co-Executive Producer',
			'Casting Associate',
			'Researcher',
			'Production Coordinator',
			'Consulting Producer',
			'Supervising Producer',
			'Senior Executive Consultant',
			'Unit Manager',
			'ADR Voice Casting',
			'Assistant Production Coordinator',
			'Assistant Production Manager',
			'Casting Assistant',
			'Casting Consultant',
			'Coordinating Producer',
			'Local Casting',
			'Script Researcher',
			'Accountant',
			'Accounting Clerk Assistant',
			'Accounting Supervisor',
			'Accounting Trainee',
			'Additional Casting',
			'Additional Production Assistant',
			'Additional Post-Production Supervisor',
			'Art Department Production Assistant',
			'Assistant Accountant',
			'Assistant Extras Casting',
			'Assistant Location Manager',
			'Assistant Unit Manager',
			'Attorney',
			'Background Casting Director',
			'Back-up Set Production Assistant',
			'Back-up Truck Production Assistant',
			'Broadcast Producer',
			'Business Affairs Coordinator',
			'Casting Coordinator',
			'Casting Director',
			'Casting Producer',
			'Casting Researcher',
			'Consulting Accountant',
			'Contract Manager',
			'Controller',
			'Data Management Technician',
			'Delegated Producer',
			'Development Producer',
			'Director of Operations',
			'Executive Assistant',
			'Executive Co-Producer',
			"Executive Producer's Assistant",
			'Extras Casting',
			'Extras Casting Assistant',
			'Extras Casting Coordinator',
			'Feature Finishing Producer',
			'Finishing Producer',
			'First Assistant Accountant',
			'First Assistant Production Coordinator',
			'General Manager',
			'Grip Production Assistant',
			'Head of Production',
			'Head of Programming',
			'Head of Research',
			'Human Resources',
			'Insert Unit Location Manager',
			'Key Accountant',
			'Key Art Production Assistant',
			'Key Grip Production Assistant',
			'Key Production Assistant',
			'Key Set Production Assistant',
			'Locale Casting Director',
			'Location Assistant',
			'Location Casting',
			'Location Coordinator',
			'Location Production Assistant',
			'Musical Casting',
			'Original Casting',
			'Payroll Accountant',
			'Post Coordinator',
			'Post Producer',
			'Post Production Accountant',
			'Post Production Coordinator',
			'Post Production Producer',
			'Post Production Technical Engineer',
			"Producer's Assistant",
			'Production Assistant',
			'Production Consultant',
			'Production Designer',
			'Production Driver',
			'Production Executive',
			'Production Runner',
			'Production Secretary',
			'Production Trainee',
			'Research Assistant',
			'Second Assistant Accountant',
			'Second Assistant Production Coordinator',
			'Second Assistant Unit Manager',
			'Second Unit Location Manager',
			'Street Casting',
			'Trainee Production Coordinator',
			'Travel Coordinator',
			'Truck Production Assistant',
			'Unit Swing',
		],
	},
	{
		department: 'Visual Effects',
		jobs: [
			'Animation',
			'Visual Effects',
			'Chief Technician / Stop-Motion Expert',
			'Creature Design',
			'Shading',
			'Modeling',
			'CG Painter',
			'Visual Development',
			'Animation Manager',
			'Animation Director',
			'Fix Animator',
			'Animation Department Coordinator',
			'Animation Fix Coordinator',
			'Animation Production Assistant',
			'Visual Effects Supervisor',
			'Mechanical & Creature Designer',
			'Battle Motion Coordinator',
			'Animation Supervisor',
			'VFX Supervisor',
			'Cloth Setup',
			'VFX Artist',
			'CG Engineer',
			'24 Frame Playback',
			'Imaging Science',
			'I/O Supervisor',
			'Visual Effects Producer',
			'VFX Production Coordinator',
			'I/O Manager',
			'Additional Effects Development',
			'Color Designer',
			'Simulation & Effects Production Assistant',
			'Simulation & Effects Artist',
			'Pyrotechnic Supervisor',
			'Special Effects Supervisor',
			'3D Supervisor',
			'3D Director',
			'Digital Compositor',
			'Visual Effects Coordinator',
			'VFX Editor',
			'2D Artist',
			'2D Supervisor',
			'3D Animator',
			'3D Artist',
			'3D Coordinator',
			'3D Generalist',
			'3D Modeller',
			'3D Sequence Supervisor',
			'3D Tracking Layout',
			'CG Animator',
			'CGI Director',
			'Character Designer',
			'Character Modelling Supervisor',
			'Creature Technical Director',
			'Digital Effects Producer',
			'Key Animation',
			'Lead Animator',
			'Lead Character Designer',
			'Matchmove Supervisor',
			'Mechanical Designer',
			'Opening/Ending Animation',
			'Pre-Visualization Supervisor',
			'Roto Supervisor',
			'Stereoscopic Coordinator',
			'VFX Director of Photography',
			'VFX Lighting Artist',
			'Visual Effects Designer',
			'Visual Effects Technical Director',
			'2D Sequence Supervisor',
			'Additional Visual Effects',
			'Animation Coordinator',
			'Animation Technical Director',
			'CG Artist',
			'Compositing Artist',
			'Compositing Lead',
			'Compositing Supervisor',
			'Creature Effects Technical Director',
			'Cyber Scanning Supervisor',
			'Digital Film Recording',
			'Director of Previsualization',
			'Effects Supervisor',
			'Generalist',
			'Head of Animation',
			'Layout Supervisor',
			'Lead Creature Designer',
			'Matte Painter',
			'Modelling Supervisor',
			'Pipeline Technical Director',
			'Photo Retouching',
			'Pre-Visualization Coordinator',
			'Rotoscoping Artist',
			'Senior Animator',
			'Senior Generalist',
			'Senior Modeller',
			'Senior Visual Effects Supervisor',
			'Smoke Artist',
			'Stereoscopic Supervisor',
			'Stereoscopic Technical Director',
			'Supervising Animation Director',
			'Visual Effects Assistant Editor',
			'Visual Effects Camera',
			'Visual Effects Compositor',
			'Visual Effects Director',
			'Visual Effects Lineup',
			'Visual Effects Production Assistant',
			'Visual Effects Production Manager',
		],
	},
	{
		department: 'Editing',
		jobs: [
			'Editor',
			'Supervising Film Editor',
			'Additional Editing',
			'Editorial Manager',
			'First Assistant Editor',
			'Additional Editorial Assistant',
			'Editorial Coordinator',
			'Editorial Production Assistant',
			'Editorial Services',
			'Archival Footage Coordinator',
			'Archival Footage Research',
			'Color Timer',
			'Digital Intermediate',
			'Other',
			'Assistant Editor',
			'Associate Editor',
			'Co-Editor',
			'Negative Cutter',
			'3D Digital Colorist',
			'3D Editor',
			'Additional Colorist',
			'Additional Editor',
			'Assistant Picture Editor',
			'Atmos Editor',
			'Color Assistant',
			'Color Grading',
			'Colorist',
			'Consulting Editor',
			'Dailies Manager',
			'Dailies Operator',
			'Dailies Technician',
			'Digital Color Timer',
			'Digital Colorist',
			'Digital Conform Editor',
			'Digital Intermediate Assistant',
			'Digital Intermediate Colorist',
			'Digital Intermediate Data Wrangler',
			'Digital Intermediate Editor',
			'Digital Intermediate Producer',
			'Editorial Consultant',
			'EPK Editor',
			'First Assistant Picture Editor',
			'Lead Editor',
			'Online Editor',
			'Project Manager',
			'Senior Colorist',
			'Senior Digital Intermediate Colorist',
			'Stereoscopic Editor',
			'Supervising Editor',
		],
	},
	{
		department: 'Crew',
		jobs: [
			'Special Effects',
			'Post Production Supervisor',
			'Second Unit',
			'Choreographer',
			'Stunts',
			'Stunt Coordinator',
			'Special Effects Coordinator',
			'Supervising Technical Director',
			'Supervising Animator',
			'Production Artist',
			'Sequence Lead',
			'Second Film Editor',
			'Temp Music Editor',
			'Temp Sound Editor',
			'Sequence Supervisor',
			'Software Team Lead',
			'Software Engineer',
			'Documentation & Support',
			'Machinist',
			'Photoscience Manager',
			'Department Administrator',
			'Schedule Coordinator',
			'Supervisor of Production Resources',
			'Production Office Assistant',
			'Information Systems Manager',
			'Systems Administrators & Support',
			'Projection',
			'Post Production Assistant',
			'Sound Design Assistant',
			'Mix Technician',
			'Motion Actor',
			'Sets & Props Supervisor',
			'Compositor',
			'Tattooist',
			'Sets & Props Artist',
			'Motion Capture Artist',
			'Sequence Artist',
			'Mixing Engineer',
			'Special Sound Effects',
			'Post-Production Manager',
			'Dialect Coach',
			'Picture Car Coordinator',
			'Cableman',
			'Set Production Assistant',
			'Video Assist Operator',
			'Unit Publicist',
			'Set Medic',
			'Stand In',
			'Transportation Coordinator',
			'Transportation Captain',
			'Post Production Consulting',
			'Production Intern',
			'Utility Stunts',
			"Actor's Assistant",
			'Set Production Intern',
			'Production Controller',
			'Studio Teacher',
			'Chef',
			'Craft Service',
			'Scenic Artist',
			'Propmaker',
			'Prop Maker',
			'Transportation Co-Captain',
			'Driver',
			'Security',
			'Second Unit Cinematographer',
			'Loader',
			'Manager of Operations',
			'Quality Control Supervisor',
			'Legal Services',
			'Public Relations',
			'Score Engineer',
			'Translator',
			'Title Graphics',
			'Telecine Colorist',
			'Animatronic and Prosthetic Effects',
			'Martial Arts Choreographer',
			'Cinematography',
			'Steadycam',
			'Executive Visual Effects Producer',
			'Visual Effects Design Consultant',
			'Digital Effects Supervisor',
			'Digital Producer',
			'CG Supervisor',
			'Visual Effects Art Director',
			'Visual Effects Editor',
			'Executive in Charge of Finance',
			'Associate Choreographer',
			'Makeup Effects',
			'Treatment',
			'Dramaturgy',
			'Lighting Camera',
			'Technical Supervisor',
			'CGI Supervisor',
			'Creative Consultant',
			'Script',
			'Executive Music Producer',
			'Commissioning Editor',
			'Additional Writing',
			'Additional Music',
			'Poem',
			'Thanks',
			'Creator',
			'Additional Dialogue',
			'Video Game',
			'Graphic Novel Illustrator',
			'Other',
			'Series Writer',
			'Radio Play',
			'Armorer',
			'Carpenter',
			'Editorial Staff',
			'Aerial Coordinator',
			'Animal Coordinator',
			'Animal Wrangler',
			'Animatronics Designer',
			'Drone Operator',
			'In Memory Of',
			'Pilot',
			'Presenter',
			'Animatronics Supervisor',
			'Armory Coordinator',
			'Digital Effects Producer',
			'Fight Choreographer',
			'Marine Coordinator',
			'Pyrotechnician',
			'Techno Crane Operator',
			'Acting Double',
			'Additional Script Supervisor',
			'Administrative Assistant',
			'Assistant Chef',
			'Assistant Craft Service',
			'Assistant Picture Car Coordinator',
			'Assistant Script',
			'Assistant Vehicles Coordinator',
			'Base Camp Operator',
			'Captain Driver',
			'Cast Driver',
			'Catering',
			'Catering Head Chef',
			'Chaperone',
			'Chaperone Tutor',
			'Charge Scenic Artist',
			'Child Wrangler',
			'Clearances Coordinator',
			'Clearances Consultant',
			'Dialogue Coach',
			'Digital Supervisor',
			'Director of Communications',
			'File Footage',
			'Film Processor',
			'Floor Runner',
			'Generator Operator',
			'Head Driver',
			'Health and Safety',
			'Interactive Manager',
			'Intern',
			'Key Scenic Artist',
			'Key Special Effects',
			'Logistics Coordinator',
			'Marine Pilot',
			'Master at Arms',
			'Medical Consultant',
			'Military Consultant',
			'Playback Coordinator',
			'Police Consultant',
			'Post Production Scripts',
			'Receptionist',
			'Scientific Consultant',
			'Security Coordinator',
			'Series Publicist',
			'Set Runner',
			'Special Effects Assistant',
			'Special Effects Best Boy',
			'Special Effects Manager',
			'Special Effects Technician',
			'Specialized Driver',
			'Sponsorship Coordinator',
			'Sponsorship Director',
			'Stunt Double',
			'Stunt Driver',
			'Supervising Armorer',
			'Technical Advisor',
			'Transcriptions',
			'Unit Medic',
			'Vehicles Coordinator',
			'Vehicles Wrangler',
			'Weapons Master',
			'Weapons Wrangler',
		],
	},
	{
		department: 'Lighting',
		jobs: [
			'Lighting Technician',
			'Best Boy Electric',
			'Gaffer',
			'Rigging Gaffer',
			'Lighting Supervisor',
			'Lighting Manager',
			'Directing Lighting Artist',
			'Master Lighting Artist',
			'Lighting Artist',
			'Lighting Coordinator',
			'Lighting Production Assistant',
			'Best Boy Electrician',
			'Electrician',
			'Rigging Grip',
			'Other',
			'Chief Lighting Technician',
			'Lighting Director',
			'Rigging Supervisor',
			'Underwater Gaffer',
			'Additional Gaffer',
			'Additional Lighting Technician',
			'Assistant Chief Lighting Technician',
			'Assistant Electrician',
			'Assistant Gaffer',
			'Best Boy Lighting Technician',
			'Daily Electrics',
			'Genetator Operator',
			'Key Rigging Grip',
			'Lighting Design',
			'Lighting Programmer',
			'O.B. Lighting',
			'Standby Rigger',
		],
	},
	{
		department: 'Sound',
		jobs: [
			'Original Music Composer',
			'Sound Designer',
			'Sound Editor',
			'Sound Director',
			'Sound Mixer',
			'Music Editor',
			'Sound Effects Editor',
			'Production Sound Mixer',
			'Additional Soundtrack',
			'Supervising Sound Editor',
			'Supervising Sound Effects Editor',
			'Sound Re-Recording Mixer',
			'Recording Supervision',
			'Boom Operator',
			'Sound Montage Associate',
			'Songs',
			'Music',
			'ADR & Dubbing',
			'Sound Recordist',
			'Sound Engineer',
			'Foley',
			'Dialogue Editor',
			'Additional Music Supervisor',
			'First Assistant Sound Editor',
			'Scoring Mixer',
			'Dolby Consultant',
			'Other',
			'Music Director',
			'Orchestrator',
			'Vocal Coach',
			'Music Supervisor',
			'Sound',
			'Musician',
			'Additional Sound Re-Recording Mixer',
			'Additional Sound Re-Recordist',
			'ADR Editor',
			'ADR Supervisor',
			'Apprentice Sound Editor',
			'Assistant Music Supervisor',
			'Assistant Sound Editor',
			'Conductor',
			'Foley Editor',
			'Music Programmer',
			'Music Score Producer',
			'Playback Singer',
			'Sound Effects',
			'Sound Effects Designer',
			'Supervising ADR Editor',
			'Supervising Dialogue Editor',
			'Supervising Music Editor',
			'Theme Song Performance',
			'Utility Sound',
			'Additional Production Sound Mixer',
			'ADR Editor',
			'ADR Engineer',
			'ADR Coordinator',
			'ADR Mixer',
			'ADR Post Producer',
			'ADR Recording Engineer',
			'ADR Recordist',
			'Assistant Dialogue Editor',
			'Assistant Foley Artist',
			'Assistant Sound Designer',
			'Assistant Sound Engineer',
			'Audio Post Coordinator',
			'Digital Foley Artist',
			'Foley Artist',
			'Foley Mixer',
			'Foley Recording Engineer',
			'Foley Recordist',
			'Foley Supervisor',
			'Joint ADR Mixer',
			'Keyboard Programmer',
			'Location Sound Assistant',
			'Location Sound Mixer',
			'Location Sound Recordist',
			'Loop Group Coordinator',
			'Main Title Theme Composer',
			'Music Arranger',
			'Music Co-Supervisor',
			'Music Consultant',
			'Music Coordinator',
			'Music Producer',
			'Music Sound Design and Processing',
			'Music Supervision Assistant',
			'O.B. Sound',
			'Second Assistant Sound',
			'Sound Assistant',
			'Sound Mix Technician',
			'Sound Post Production Coordinator',
			'Sound Post Supervisor',
			'Sound Re-Recording Assistant',
			'Sound Supervisor',
			'Sound Technical Supervisor',
			'Vocals',
		],
	},
	{
		department: 'Costume & Make-Up',
		jobs: [
			'Costume Design',
			'Makeup Artist',
			'Hairstylist',
			'Set Dressing Artist',
			'Set Dressing Supervisor',
			'Set Dressing Manager',
			'Set Dressing Production Assistant',
			'Facial Setup Artist',
			'Hair Setup',
			'Costume Supervisor',
			'Set Costumer',
			'Makeup Department Head',
			'Wigmaker',
			'Shoe Design',
			'Other',
			'Co-Costume Designer',
			'Hair Department Head',
			'Hair Designer',
			'Makeup Designer',
			'Assistant Costume Designer',
			'Prosthetic Supervisor',
			'Seamstress',
			'Key Hair Stylist',
			'Ager/Dyer',
			'Costume Consultant',
			'Costume Coordinator',
			'Costume Illustrator',
			'Hair Supervisor',
			'Key Costumer',
			'Key Makeup Artist',
			'Key Set Costumer',
			'Makeup Effects Designer',
			'Makeup Supervisor',
			'Prosthetic Designer',
			'Prosthetic Makeup Artist',
			'Tailor',
			'Tattoo Designer',
			'Wardrobe Supervisor',
			'Wig Designer',
			'Additional Hairstylist',
			'Additional Wardrobe Assistant',
			'Assistant Hairstylist',
			'Assistant Hairdresser',
			'Assistant Makeup Artist',
			'Contact Lens Designer',
			'Contact Lens Painter',
			'Contact Lens Technician',
			'Costume Assistant',
			'Costume Mistress',
			'Costume Designer',
			'Costume Set Supervisor',
			'Costume Standby',
			'Costumer',
			'Daily Makeup & Hair',
			'Daily Wardrobe',
			'Dresser',
			'Extras Dresser',
			'Extras Makeup Artist',
			'First Assistant Hairstylist',
			'First Assistant Makeup Artist',
			'Hair Assistant',
			'Hairdresser',
			'Key Dresser',
			'Key Hairdresser',
			'Lead Costumer',
			'Makeup & Hair',
			'Makeup & Hair Assistant',
			'Makeup Trainee',
			'On Set Dresser',
			'Principal Costumer',
			'Prosthetics',
			'Prosthetics Painter',
			'Prosthetics Sculptor',
			'Special Effects Key Makeup Artist',
			'Special Effects Makeup Artist',
			'Truck Costumer',
			'Truck Supervisor',
			'Wardrobe Assistant',
			'Wardrobe Coordinator',
			'Wardrobe Designer',
			'Wardrobe Intern',
			'Wardrobe Master',
			'Wardrobe Specialized Technician',
		],
	},
]

export const SITES = [
	{
		label: 'YouTube',
		value: 'youtube',
	},
	{
		label: 'Vimeo',
		value: 'vimeo',
	},
]

export const VIDEO_TYPES = [
	{
		label: 'Trailer',
		value: 'trailer',
	},
	{
		label: 'Teaser',
		value: 'teaser',
	},
	{
		label: 'Clip',
		value: 'clip',
	},
	{
		label: 'Featurette',
		value: 'featurette',
	},
	{
		label: 'Behind the Scenes',
		value: 'behind the scenes',
	},
	{
		label: 'Bloopers',
		value: 'bloopers',
	},
	{
		label: 'Interview',
		value: 'interview',
	},
]

export const PHOTO_TYPES = [
	{
		label: 'Poster',
		value: 'poster',
	},
	{
		label: 'Backdrop',
		value: 'backdrop',
	},
]

export const QUALITY = [
	{
		label: 'SD',
		value: 'sd',
	},
	{
		label: 'HD',
		value: 'hd',
	},
	{
		label: '4K',
		value: '4k',
	},
]

export const GENDERS = [
	{
		label: 'Male',
		value: 'male',
	},
	{
		label: 'Female',
		value: 'female',
	},
	{
		label: 'Other',
		value: 'other',
	},
]
export const GENRES = [
	'Action',
	'Adventure',
	'Comedy',
	'Drama',
	'Fantasy',
	'Horror',
	'Thriller',
	'Western',
	'Sci-Fi',
	'Romance',
	'Crime',
	'Animation',
	'Family',
	'Mystery',
	'War',
	'History',
	'Music',
	'Sport',
	'Biography',
	'Musical',
	'Film-Noir',
	'News',
	'Talk-Show',
	'Reality-TV',
	'Game-Show',
	'Adult',
]

export const FILM_RELEASE_TYPES = [
	{
		label: 'Premiere',
		value: 'premiere',
	},
	{
		label: 'Theatrical',
		value: 'theatrical',
	},
	{
		label: 'Digital',
		value: 'digital',
	},
	{
		label: 'Physical',
		value: 'physical',
	},
	{
		label: 'TV',
		value: 'tv',
	},
]

export const FILM_SORT_OPTIONS: Array<{ label: string; value: Sort }> = [
	{ label: 'Title (A-Z)', value: { orderBy: 'title', order: 'asc' } },
	{ label: 'Title (Z-A)', value: { orderBy: 'title', order: 'desc' } },
	// {
	// 	label: 'Popularity Ascending',
	// 	value: { orderBy: 'popularity', order: 'asc' },
	// },
	// {
	// 	label: 'Popularity Descending',
	// 	value: { orderBy: 'popularity', order: 'desc' },
	// },
	{
		label: 'Rating Ascending',
		value: { orderBy: 'voteAverage', order: 'asc' },
	},
	{
		label: 'Rating Descending',
		value: { orderBy: 'voteAverage', order: 'desc' },
	},
	{
		label: 'Release Date Ascending',
		value: { orderBy: 'releaseDate', order: 'asc' },
	},
	{
		label: 'Release Date Descending',
		value: { orderBy: 'releaseDate', order: 'desc' },
	},
]

export const PEOPLE_SORT_OPTIONS: Array<{ label: string; value: Sort }> = [
	{ label: 'Name (A-Z)', value: { orderBy: 'name', order: 'asc' } },
	{ label: 'Name (Z-A)', value: { orderBy: 'name', order: 'desc' } },
	{
		label: 'View Count (Ascending)',
		value: { orderBy: 'viewCount', order: 'asc' },
	},
	{
		label: 'View Count (Descending)',
		value: { orderBy: 'viewCount', order: 'desc' },
	},
	// {
	// 	label: 'Popularity Ascending',
	// 	value: { orderBy: 'popularity', order: 'asc' },
	// },
	// {
	// 	label: 'Popularity Descending',
	// 	value: { orderBy: 'popularity', order: 'desc' },
	// },
]

export const oneWeekAgo = () =>
	new Date(new Date().setDate(new Date().getDate() - 7))

// NOTE: This is max file size
export const MAX_SIZE = 1024 * 1024 * 3 // 3MB
