import { Payment } from './columns'

export const payments: Payment[] = [
	{
		id: 'f4d5a1b8',
		amount: 87,
		status: 'completed',
		email: 'alice@example.com',
	},
	{
		id: 'a8c9e0f1',
		amount: 125,
		status: 'pending',
		email: 'bob@gmail.com',
	},
	{
		id: 'c3b7e2d4',
		amount: 45,
		status: 'failed',
		email: 'charlie@yahoo.com',
	},
	{
		id: 'd7e8f9a3',
		amount: 200,
		status: 'completed',
		email: 'david@hotmail.com',
	},
	{
		id: 'e2f9a7b6',
		amount: 112,
		status: 'processing',
		email: 'eve@example.com',
	},
	{
		id: 'f3b2e4c7',
		amount: 60,
		status: 'pending',
		email: 'frank@outlook.com',
	},
	{
		id: 'g1c5d6a8',
		amount: 98,
		status: 'failed',
		email: 'grace@example.com',
	},
	{
		id: 'h2d9f8b3',
		amount: 150,
		status: 'completed',
		email: 'harry@yahoo.com',
	},
	{
		id: 'i7b3e1c2',
		amount: 175,
		status: 'processing',
		email: 'irene@gmail.com',
	},
	{
		id: 'j5a2c7d4',
		amount: 215,
		status: 'pending',
		email: 'jack@example.com',
	},
	{
		id: 'k9e3d8a1',
		amount: 132,
		status: 'failed',
		email: 'karen@hotmail.com',
	},
	{
		id: 'l8c1b6e5',
		amount: 90,
		status: 'completed',
		email: 'leo@gmail.com',
	},
	{
		id: 'm6b7e2f9',
		amount: 145,
		status: 'processing',
		email: 'mary@example.com',
	},
	{
		id: 'n4f2a8c3',
		amount: 170,
		status: 'pending',
		email: 'nancy@yahoo.com',
	},
	{
		id: 'o3d5b1e7',
		amount: 120,
		status: 'failed',
		email: 'oliver@gmail.com',
	},
	{
		id: 'p7e4c9f2',
		amount: 200,
		status: 'completed',
		email: 'paul@example.com',
	},
	{
		id: 'q1a8d7c4',
		amount: 110,
		status: 'processing',
		email: 'quincy@hotmail.com',
	},
	{
		id: 'r5b3e6a9',
		amount: 160,
		status: 'pending',
		email: 'rachel@yahoo.com',
	},
	{
		id: 's8c2f9d1',
		amount: 85,
		status: 'failed',
		email: 'sam@gmail.com',
	},
	{
		id: 't2a7b5e3',
		amount: 195,
		status: 'completed',
		email: 'tina@example.com',
	},
	{
		id: 'u6c3e1f8',
		amount: 140,
		status: 'processing',
		email: 'ursula@hotmail.com',
	},
	{
		id: 'v9d4b2c7',
		amount: 180,
		status: 'pending',
		email: 'victor@gmail.com',
	},
	{
		id: 'w7e2f8a4',
		amount: 100,
		status: 'failed',
		email: 'wendy@example.com',
	},
	{
		id: 'x3a5d1c9',
		amount: 205,
		status: 'completed',
		email: 'xander@yahoo.com',
	},
	{
		id: 'y8b6f7d3',
		amount: 130,
		status: 'processing',
		email: 'yvonne@hotmail.com',
	},
	{
		id: 'z5c1e3f2',
		amount: 165,
		status: 'pending',
		email: 'zach@example.com',
	},
	{
		id: 'a4d9e7b6',
		amount: 125,
		status: 'failed',
		email: 'andrew@gmail.com',
	},
	{
		id: 'b7f2c3d1',
		amount: 150,
		status: 'completed',
		email: 'beth@example.com',
	},
	{
		id: 'c9e8b5a4',
		amount: 135,
		status: 'processing',
		email: 'claire@yahoo.com',
	},
	{
		id: 'd3a6f7c2',
		amount: 210,
		status: 'pending',
		email: 'daniel@hotmail.com',
	},
	{
		id: 'e5c2d9f1',
		amount: 95,
		status: 'failed',
		email: 'emma@example.com',
	},
	{
		id: 'f8b7e3a4',
		amount: 175,
		status: 'completed',
		email: 'felix@gmail.com',
	},
	{
		id: 'g2d1a6f3',
		amount: 115,
		status: 'processing',
		email: 'grace@hotmail.com',
	},
	{
		id: 'h6c5f4b2',
		amount: 190,
		status: 'pending',
		email: 'hannah@example.com',
	},
	{
		id: 'i9a3e7d5',
		amount: 105,
		status: 'failed',
		email: 'ian@yahoo.com',
	},
	{
		id: 'j7f4c2b1',
		amount: 155,
		status: 'completed',
		email: 'jane@gmail.com',
	},
	{
		id: 'k5b6e8f9',
		amount: 130,
		status: 'processing',
		email: 'kevin@hotmail.com',
	},
	{
		id: 'l2c9d7a3',
		amount: 185,
		status: 'pending',
		email: 'lucy@example.com',
	},
	{
		id: 'm4e8f1c6',
		amount: 140,
		status: 'failed',
		email: 'michael@yahoo.com',
	},
	{
		id: 'n3b2a9d7',
		amount: 165,
		status: 'completed',
		email: 'nina@gmail.com',
	},
	{
		id: 'o6d5f4c2',
		amount: 95,
		status: 'processing',
		email: 'oscar@hotmail.com',
	},
	{
		id: 'p9e7a1b6',
		amount: 220,
		status: 'pending',
		email: 'peter@example.com',
	},
	{
		id: 'q5c3f8d9',
		amount: 145,
		status: 'failed',
		email: 'quinn@yahoo.com',
	},
	{
		id: 'r8b7e2a4',
		amount: 210,
		status: 'completed',
		email: 'rita@hotmail.com',
	},
	{
		id: 's1d3f5c6',
		amount: 130,
		status: 'processing',
		email: 'steve@gmail.com',
	},
	{
		id: 't7e9b4f2',
		amount: 180,
		status: 'pending',
		email: 'tara@example.com',
	},
	{
		id: 'u6f8a3d1',
		amount: 110,
		status: 'failed',
		email: 'uma@gmail.com',
	},
	{
		id: 'v2c5e7b4',
		amount: 160,
		status: 'completed',
		email: 'vince@hotmail.com',
	},
	{
		id: 'w9b3f6d2',
		amount: 150,
		status: 'processing',
		email: 'wendy@yahoo.com',
	},
	{
		id: 'x4d8a2e9',
		amount: 190,
		status: 'pending',
		email: 'xavier@example.com',
	},
]
